//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SailingPeople.Resources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SailingPeople.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Boat Type.
        /// </summary>
        public static string BoatType
        {
            get
            {
                return ResourceManager.GetString("BoatType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cabin.
        /// </summary>
        public static string Cabin
        {
            get
            {
                return ResourceManager.GetString("Cabin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories
        {
            get
            {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string CategoryName
        {
            get
            {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact
        {
            get
            {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Faq.
        /// </summary>
        public static string Faq
        {
            get
            {
                return ResourceManager.GetString("Faq", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter the cabin number.
        /// </summary>
        public static string FilterCabinInput
        {
            get
            {
                return ResourceManager.GetString("FilterCabinInput", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter the number of guests.
        /// </summary>
        public static string FilterGuestInput
        {
            get
            {
                return ResourceManager.GetString("FilterGuestInput", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        public static string Guest
        {
            get
            {
                return ResourceManager.GetString("Guest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Embark on an unforgettable sea voyage with comfortable boats and unique routes..
        /// </summary>
        public static string HeaderSubText
        {
            get
            {
                return ResourceManager.GetString("HeaderSubText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Discover Freedom in the Blue.
        /// </summary>
        public static string HeaderText
        {
            get
            {
                return ResourceManager.GetString("HeaderText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home
        {
            get
            {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Inspect.
        /// </summary>
        public static string Inspect
        {
            get
            {
                return ResourceManager.GetString("Inspect", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Required field!.
        /// </summary>
        public static string RequiredFieldd
        {
            get
            {
                return ResourceManager.GetString("RequiredFieldd", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search
        {
            get
            {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select
        {
            get
            {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Category
        {
            get
            {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string FollowUs
        {
            get
            {
                return ResourceManager.GetString("FollowUs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string ContactInformation
        {
            get
            {
                return ResourceManager.GetString("ContactInformation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Pages
        {
            get
            {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string FindUs
        {
            get
            {
                return ResourceManager.GetString("FindUs", resourceCulture);
            }
        }
    }
}
